//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKR.Exception {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceErrorMessage_it {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessage_it() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OKR.Exception.ResourceErrorMessage_it", typeof(ResourceErrorMessage_it).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        internal static string TITLE_IS_REQUIRED {
            get {
                return ResourceManager.GetString("TITLE_IS_REQUIRED", resourceCulture);
            }
        }
        
        internal static string OBJECTIVE_YEAR_IS_REQUIRED {
            get {
                return ResourceManager.GetString("OBJECTIVE_YEAR_IS_REQUIRED", resourceCulture);
            }
        }
        
        internal static string OBJECTIVE_QUARTER_IS_REQUIRED {
            get {
                return ResourceManager.GetString("OBJECTIVE_QUARTER_IS_REQUIRED", resourceCulture);
            }
        }
        
        internal static string TITLE_MINIMUM_CHARACTERS {
            get {
                return ResourceManager.GetString("TITLE_MINIMUM_CHARACTERS", resourceCulture);
            }
        }
        
        internal static string OBJECTIVE_TITLE_MAXIMUM_CHARACTERS {
            get {
                return ResourceManager.GetString("OBJECTIVE_TITLE_MAXIMUM_CHARACTERS", resourceCulture);
            }
        }
        
        internal static string OBJECTIVE_YEAR_INVALID {
            get {
                return ResourceManager.GetString("OBJECTIVE_YEAR_INVALID", resourceCulture);
            }
        }
        
        internal static string OBJECTIVE_QUARTER_INVALID {
            get {
                return ResourceManager.GetString("OBJECTIVE_QUARTER_INVALID", resourceCulture);
            }
        }
        
        internal static string OBJECTIVE_NOT_FOUND {
            get {
                return ResourceManager.GetString("OBJECTIVE_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string KEY_RESULT_TITLE_MAXIMUM_CHARACTERS {
            get {
                return ResourceManager.GetString("KEY_RESULT_TITLE_MAXIMUM_CHARACTERS", resourceCulture);
            }
        }
        
        internal static string KEY_RESULT_NUMBER_IS_REQUIRED {
            get {
                return ResourceManager.GetString("KEY_RESULT_NUMBER_IS_REQUIRED", resourceCulture);
            }
        }
        
        internal static string KEY_RESULT_NUMBER_INVALID {
            get {
                return ResourceManager.GetString("KEY_RESULT_NUMBER_INVALID", resourceCulture);
            }
        }
        
        internal static string KEY_RESULT_NUMBER_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("KEY_RESULT_NUMBER_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        internal static string KEY_RESULT_TITLE_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("KEY_RESULT_TITLE_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        internal static string OBJECTIVE_HAS_5_KEY_RESULT {
            get {
                return ResourceManager.GetString("OBJECTIVE_HAS_5_KEY_RESULT", resourceCulture);
            }
        }
        
        internal static string KEY_RESULT_NOT_FOUND {
            get {
                return ResourceManager.GetString("KEY_RESULT_NOT_FOUND", resourceCulture);
            }
        }
    }
}
